- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go
      - dep
      - protobuf
      - homebrew/php/php71

    homebrew_cask_apps:
      - phpstorm
      - goland
      - sequel-pro
      - java

  roles:
    - geerlingguy.homebrew
