# vim: nospell shiftwidth=2 :
- hosts: localhost

  vars:

    mas_installed_apps:
      - { id: 497799835, name: "XCode" }
      - { id: 919269455, name: "Stufflt Expander" }
      - { id: 560459030, name: "Yandex.Disk" }
      - { id: 410628904, name: "Wunderlist" }

    homebrew_installed_packages:
      - bash-completion
      - bash-git-prompt
      - git
      - jq
      - bat
      - fish
      - { name: vim, install_options: "override-system-vi" }

    homebrew_cask_apps:

      # Browsers and network utilities
      - google-chrome
      - firefox
      - transmission

      # Messengers
      - skype
      - telegram
      - whatsapp

      # Others
      - alfred
      - iterm2
      - keepassx
      - dropbox
      - yandex-disk
      - virtualbox
      - docker

  roles:
    - geerlingguy.homebrew
    - geerlingguy.mas
