- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go@1.12
      - protobuf
      - bats-core
      - npm
      - shellcheck
      - kubectl

    homebrew_cask_apps:
      - goland
      - sequel-pro
      - java
      - slack

  roles:
    - geerlingguy.homebrew
