#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go
      - protobuf
      - python3
      - golangci/tap/golangci-lint
      - osxfuse

    homebrew_cask_apps:
      - goland
      - java
      - bloomrpc
      - zoomus

  roles:
    - geerlingguy.homebrew
